### PR TITLE
Fix build with mysql-connector-c v8.0.18

### PR DESCRIPTION
**Pull request by devurandom**
This fixes following compilation failure with version 8.0.18 of
mysql-connector-c:
```
rdf_storage_mysql.c: In function 'librdf_storage_mysql_get_handle':
rdf_storage_mysql.c:450:5: error: unknown type name 'my_bool'; did you mean 'bool'?
  450 |     my_bool value=(context->reconnect) ? 1 : 0;
      |     ^~~~~~~
      |     bool
make[3]: *** [Makefile:886: librdf_storage_mysql_la-rdf_storage_mysql.lo] Error 1
```

The correct type for calling `mysql_options` with `MYSQL_OPT_RECONNECT`
in version 8.0 of the library is `bool*`:
https://dev.mysql.com/doc/refman/8.0/en/mysql-options.html

See-Also: https://bugs.gentoo.org/692462

### CODE REVIEW

**Comment by bodograumann** [comment]
I don’t think you can simply replace it like that, because the code must work with mysql-connector-c version 5 and version 8.
